
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox17;
	private global::Gtk.Label label5;
	private global::Gtk.Entry txtSettingUrl;
	private global::Gtk.Label GtkLabel;
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.Notebook nbTabs;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment GtkAlignment3;
	private global::Gtk.VBox vbox5;
	private global::Gtk.RadioButton radQueryAllPOIs;
	private global::Gtk.HBox hbox2;
	private global::Gtk.RadioButton radQueryWithID;
	private global::Gtk.Entry txtQueryID;
	private global::Gtk.HBox hbox3;
	private global::Gtk.RadioButton radQueryWithAttribute;
	private global::Gtk.ComboBox cmbQueryAttributeName;
	private global::Gtk.Label label6;
	private global::Gtk.Entry txtQueryAttributeValue;
	private global::Gtk.Button btnSearch;
	private global::Gtk.Label GtkLabel5;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment2;
	private global::Gtk.VBox vbox4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView tvPOIs;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button btnEdit;
	private global::Gtk.Button btnDelete;
	private global::Gtk.Label GtkLabel8;
	private global::Gtk.Label label1;
	private global::Gtk.VBox vbox6;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label7;
	private global::Gtk.Entry txtNewName;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label8;
	private global::Gtk.Entry txtNewLatitude;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label24;
	private global::Gtk.Entry txtNewLongitude;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label98;
	private global::Gtk.Entry txtNewCreator;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Label label88;
	private global::Gtk.Entry txtNewDescription;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Label lbl34;
	private global::Gtk.Entry txtNewCategory;
	private global::Gtk.Button btnInsert;
	private global::Gtk.Label label2;
	private global::Gtk.VBox vbox7;
	private global::Gtk.HBox hbox16;
	private global::Gtk.Label label19;
	private global::Gtk.Entry txtUpdateId;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Label label13;
	private global::Gtk.Entry txtUpdateName;
	private global::Gtk.HBox hbox11;
	private global::Gtk.Label label14;
	private global::Gtk.Entry txtUpdateLatitude;
	private global::Gtk.HBox hbox12;
	private global::Gtk.Label label15;
	private global::Gtk.Entry txtUpdateLongitude;
	private global::Gtk.HBox hbox13;
	private global::Gtk.Label label16;
	private global::Gtk.Entry txtUpdateCreator;
	private global::Gtk.HBox hbox14;
	private global::Gtk.Label label17;
	private global::Gtk.Entry txtUpdateDescription;
	private global::Gtk.HBox hbox15;
	private global::Gtk.Label label18;
	private global::Gtk.Entry txtUpdateCategory;
	private global::Gtk.Button btnUpdate;
	private global::Gtk.Label label3;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView tvLogging;
	private global::Gtk.Label GtkLabel11;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("FH Point of Interest App");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frame1.BorderWidth = ((uint)(10));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		this.GtkAlignment.RightPadding = ((uint)(12));
		this.GtkAlignment.BottomPadding = ((uint)(6));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox ();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Server URL:");
		this.hbox17.Add (this.label5);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label5]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.txtSettingUrl = new global::Gtk.Entry ();
		this.txtSettingUrl.CanFocus = true;
		this.txtSettingUrl.Name = "txtSettingUrl";
		this.txtSettingUrl.IsEditable = true;
		this.txtSettingUrl.InvisibleChar = '●';
		this.hbox17.Add (this.txtSettingUrl);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.txtSettingUrl]));
		w2.Position = 1;
		this.vbox2.Add (this.hbox17);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox17]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		this.GtkAlignment.Add (this.vbox2);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel = new global::Gtk.Label ();
		this.GtkLabel.Name = "GtkLabel";
		this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Settings</b>");
		this.GtkLabel.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 412;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.nbTabs = new global::Gtk.Notebook ();
		this.nbTabs.CanFocus = true;
		this.nbTabs.Name = "nbTabs";
		this.nbTabs.CurrentPage = 0;
		this.nbTabs.BorderWidth = ((uint)(10));
		// Container child nbTabs.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frame4.BorderWidth = ((uint)(4));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		this.GtkAlignment3.RightPadding = ((uint)(12));
		this.GtkAlignment3.BottomPadding = ((uint)(6));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.radQueryAllPOIs = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("all POIs"));
		this.radQueryAllPOIs.CanFocus = true;
		this.radQueryAllPOIs.Name = "radQueryAllPOIs";
		this.radQueryAllPOIs.DrawIndicator = true;
		this.radQueryAllPOIs.UseUnderline = true;
		this.radQueryAllPOIs.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox5.Add (this.radQueryAllPOIs);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.radQueryAllPOIs]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.radQueryWithID = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("with ID:"));
		this.radQueryWithID.CanFocus = true;
		this.radQueryWithID.Name = "radQueryWithID";
		this.radQueryWithID.DrawIndicator = true;
		this.radQueryWithID.UseUnderline = true;
		this.radQueryWithID.Group = this.radQueryAllPOIs.Group;
		this.hbox2.Add (this.radQueryWithID);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.radQueryWithID]));
		w8.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtQueryID = new global::Gtk.Entry ();
		this.txtQueryID.CanFocus = true;
		this.txtQueryID.Name = "txtQueryID";
		this.txtQueryID.IsEditable = true;
		this.txtQueryID.InvisibleChar = '●';
		this.hbox2.Add (this.txtQueryID);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtQueryID]));
		w9.Position = 1;
		this.vbox5.Add (this.hbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.radQueryWithAttribute = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("with attribute:"));
		this.radQueryWithAttribute.CanFocus = true;
		this.radQueryWithAttribute.Name = "radQueryWithAttribute";
		this.radQueryWithAttribute.DrawIndicator = true;
		this.radQueryWithAttribute.UseUnderline = true;
		this.radQueryWithAttribute.Group = this.radQueryAllPOIs.Group;
		this.hbox3.Add (this.radQueryWithAttribute);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.radQueryWithAttribute]));
		w11.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.cmbQueryAttributeName = global::Gtk.ComboBox.NewText ();
		this.cmbQueryAttributeName.Name = "cmbQueryAttributeName";
		this.hbox3.Add (this.cmbQueryAttributeName);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.cmbQueryAttributeName]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("=");
		this.hbox3.Add (this.label6);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label6]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.txtQueryAttributeValue = new global::Gtk.Entry ();
		this.txtQueryAttributeValue.CanFocus = true;
		this.txtQueryAttributeValue.Name = "txtQueryAttributeValue";
		this.txtQueryAttributeValue.IsEditable = true;
		this.txtQueryAttributeValue.InvisibleChar = '●';
		this.hbox3.Add (this.txtQueryAttributeValue);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtQueryAttributeValue]));
		w14.Position = 3;
		this.vbox5.Add (this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox3]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.btnSearch = new global::Gtk.Button ();
		this.btnSearch.CanFocus = true;
		this.btnSearch.Name = "btnSearch";
		this.btnSearch.UseUnderline = true;
		this.btnSearch.Label = global::Mono.Unix.Catalog.GetString ("Search");
		this.vbox5.Add (this.btnSearch);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.btnSearch]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		this.GtkAlignment3.Add (this.vbox5);
		this.frame4.Add (this.GtkAlignment3);
		this.GtkLabel5 = new global::Gtk.Label ();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Parameters</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel5;
		this.vbox3.Add (this.frame4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame4]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frame3.BorderWidth = ((uint)(4));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		this.GtkAlignment2.RightPadding = ((uint)(12));
		this.GtkAlignment2.BottomPadding = ((uint)(6));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tvPOIs = new global::Gtk.TreeView ();
		this.tvPOIs.CanFocus = true;
		this.tvPOIs.Name = "tvPOIs";
		this.GtkScrolledWindow1.Add (this.tvPOIs);
		this.vbox4.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow1]));
		w21.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnEdit = new global::Gtk.Button ();
		this.btnEdit.WidthRequest = 60;
		this.btnEdit.CanFocus = true;
		this.btnEdit.Name = "btnEdit";
		this.btnEdit.UseUnderline = true;
		this.btnEdit.Label = global::Mono.Unix.Catalog.GetString ("Edit");
		this.hbox1.Add (this.btnEdit);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnEdit]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnDelete = new global::Gtk.Button ();
		this.btnDelete.WidthRequest = 60;
		this.btnDelete.CanFocus = true;
		this.btnDelete.Name = "btnDelete";
		this.btnDelete.UseUnderline = true;
		this.btnDelete.Label = global::Mono.Unix.Catalog.GetString ("Delete");
		this.hbox1.Add (this.btnDelete);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnDelete]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox4.Add (this.hbox1);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.GtkAlignment2.Add (this.vbox4);
		this.frame3.Add (this.GtkAlignment2);
		this.GtkLabel8 = new global::Gtk.Label ();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>POIs</b>");
		this.GtkLabel8.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel8;
		this.vbox3.Add (this.frame3);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame3]));
		w27.Position = 1;
		this.nbTabs.Add (this.vbox3);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Query");
		this.nbTabs.SetTabLabel (this.vbox3, this.label1);
		this.label1.ShowAll ();
		// Container child nbTabs.Gtk.Notebook+NotebookChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		this.vbox6.BorderWidth = ((uint)(10));
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.WidthRequest = 100;
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
		this.hbox4.Add (this.label7);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label7]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.txtNewName = new global::Gtk.Entry ();
		this.txtNewName.CanFocus = true;
		this.txtNewName.Name = "txtNewName";
		this.txtNewName.IsEditable = true;
		this.txtNewName.InvisibleChar = '●';
		this.hbox4.Add (this.txtNewName);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.txtNewName]));
		w30.Position = 1;
		this.vbox6.Add (this.hbox4);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.WidthRequest = 100;
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Latitude:");
		this.hbox5.Add (this.label8);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label8]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.txtNewLatitude = new global::Gtk.Entry ();
		this.txtNewLatitude.CanFocus = true;
		this.txtNewLatitude.Name = "txtNewLatitude";
		this.txtNewLatitude.IsEditable = true;
		this.txtNewLatitude.InvisibleChar = '●';
		this.hbox5.Add (this.txtNewLatitude);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.txtNewLatitude]));
		w33.Position = 1;
		this.vbox6.Add (this.hbox5);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label24 = new global::Gtk.Label ();
		this.label24.WidthRequest = 100;
		this.label24.Name = "label24";
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Longitude:");
		this.hbox6.Add (this.label24);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label24]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.txtNewLongitude = new global::Gtk.Entry ();
		this.txtNewLongitude.CanFocus = true;
		this.txtNewLongitude.Name = "txtNewLongitude";
		this.txtNewLongitude.IsEditable = true;
		this.txtNewLongitude.InvisibleChar = '●';
		this.hbox6.Add (this.txtNewLongitude);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.txtNewLongitude]));
		w36.Position = 1;
		this.vbox6.Add (this.hbox6);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label98 = new global::Gtk.Label ();
		this.label98.WidthRequest = 100;
		this.label98.Name = "label98";
		this.label98.LabelProp = global::Mono.Unix.Catalog.GetString ("Creator:");
		this.hbox7.Add (this.label98);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label98]));
		w38.Position = 0;
		w38.Expand = false;
		w38.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.txtNewCreator = new global::Gtk.Entry ();
		this.txtNewCreator.CanFocus = true;
		this.txtNewCreator.Name = "txtNewCreator";
		this.txtNewCreator.IsEditable = true;
		this.txtNewCreator.InvisibleChar = '●';
		this.hbox7.Add (this.txtNewCreator);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.txtNewCreator]));
		w39.Position = 1;
		this.vbox6.Add (this.hbox7);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox7]));
		w40.Position = 3;
		w40.Expand = false;
		w40.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label88 = new global::Gtk.Label ();
		this.label88.WidthRequest = 100;
		this.label88.Name = "label88";
		this.label88.LabelProp = global::Mono.Unix.Catalog.GetString ("Description:");
		this.hbox8.Add (this.label88);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label88]));
		w41.Position = 0;
		w41.Expand = false;
		w41.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.txtNewDescription = new global::Gtk.Entry ();
		this.txtNewDescription.CanFocus = true;
		this.txtNewDescription.Name = "txtNewDescription";
		this.txtNewDescription.IsEditable = true;
		this.txtNewDescription.InvisibleChar = '●';
		this.hbox8.Add (this.txtNewDescription);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.txtNewDescription]));
		w42.Position = 1;
		this.vbox6.Add (this.hbox8);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox8]));
		w43.Position = 4;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.lbl34 = new global::Gtk.Label ();
		this.lbl34.WidthRequest = 100;
		this.lbl34.Name = "lbl34";
		this.lbl34.LabelProp = global::Mono.Unix.Catalog.GetString ("Category:");
		this.hbox9.Add (this.lbl34);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.lbl34]));
		w44.Position = 0;
		w44.Expand = false;
		w44.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.txtNewCategory = new global::Gtk.Entry ();
		this.txtNewCategory.CanFocus = true;
		this.txtNewCategory.Name = "txtNewCategory";
		this.txtNewCategory.IsEditable = true;
		this.txtNewCategory.InvisibleChar = '●';
		this.hbox9.Add (this.txtNewCategory);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.txtNewCategory]));
		w45.Position = 1;
		this.vbox6.Add (this.hbox9);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox9]));
		w46.Position = 5;
		w46.Expand = false;
		w46.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.btnInsert = new global::Gtk.Button ();
		this.btnInsert.CanFocus = true;
		this.btnInsert.Name = "btnInsert";
		this.btnInsert.UseUnderline = true;
		this.btnInsert.Label = global::Mono.Unix.Catalog.GetString ("Insert");
		this.vbox6.Add (this.btnInsert);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.btnInsert]));
		w47.Position = 6;
		w47.Expand = false;
		w47.Fill = false;
		this.nbTabs.Add (this.vbox6);
		global::Gtk.Notebook.NotebookChild w48 = ((global::Gtk.Notebook.NotebookChild)(this.nbTabs [this.vbox6]));
		w48.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Insert");
		this.nbTabs.SetTabLabel (this.vbox6, this.label2);
		this.label2.ShowAll ();
		// Container child nbTabs.Gtk.Notebook+NotebookChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		this.vbox7.BorderWidth = ((uint)(10));
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox ();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label ();
		this.label19.WidthRequest = 100;
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("ID:");
		this.hbox16.Add (this.label19);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.label19]));
		w49.Position = 0;
		w49.Expand = false;
		w49.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.txtUpdateId = new global::Gtk.Entry ();
		this.txtUpdateId.CanFocus = true;
		this.txtUpdateId.Name = "txtUpdateId";
		this.txtUpdateId.IsEditable = false;
		this.txtUpdateId.InvisibleChar = '●';
		this.hbox16.Add (this.txtUpdateId);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.txtUpdateId]));
		w50.Position = 1;
		this.vbox7.Add (this.hbox16);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox16]));
		w51.Position = 0;
		w51.Expand = false;
		w51.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.WidthRequest = 100;
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
		this.hbox10.Add (this.label13);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label13]));
		w52.Position = 0;
		w52.Expand = false;
		w52.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.txtUpdateName = new global::Gtk.Entry ();
		this.txtUpdateName.CanFocus = true;
		this.txtUpdateName.Name = "txtUpdateName";
		this.txtUpdateName.IsEditable = true;
		this.txtUpdateName.InvisibleChar = '●';
		this.hbox10.Add (this.txtUpdateName);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.txtUpdateName]));
		w53.Position = 1;
		this.vbox7.Add (this.hbox10);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox10]));
		w54.Position = 1;
		w54.Expand = false;
		w54.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label ();
		this.label14.WidthRequest = 100;
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Latitude:");
		this.hbox11.Add (this.label14);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label14]));
		w55.Position = 0;
		w55.Expand = false;
		w55.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.txtUpdateLatitude = new global::Gtk.Entry ();
		this.txtUpdateLatitude.CanFocus = true;
		this.txtUpdateLatitude.Name = "txtUpdateLatitude";
		this.txtUpdateLatitude.IsEditable = true;
		this.txtUpdateLatitude.InvisibleChar = '●';
		this.hbox11.Add (this.txtUpdateLatitude);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.txtUpdateLatitude]));
		w56.Position = 1;
		this.vbox7.Add (this.hbox11);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox11]));
		w57.Position = 2;
		w57.Expand = false;
		w57.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.WidthRequest = 100;
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Longitude:");
		this.hbox12.Add (this.label15);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label15]));
		w58.Position = 0;
		w58.Expand = false;
		w58.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.txtUpdateLongitude = new global::Gtk.Entry ();
		this.txtUpdateLongitude.CanFocus = true;
		this.txtUpdateLongitude.Name = "txtUpdateLongitude";
		this.txtUpdateLongitude.IsEditable = true;
		this.txtUpdateLongitude.InvisibleChar = '●';
		this.hbox12.Add (this.txtUpdateLongitude);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.txtUpdateLongitude]));
		w59.Position = 1;
		this.vbox7.Add (this.hbox12);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox12]));
		w60.Position = 3;
		w60.Expand = false;
		w60.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label ();
		this.label16.WidthRequest = 100;
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Creator:");
		this.hbox13.Add (this.label16);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label16]));
		w61.Position = 0;
		w61.Expand = false;
		w61.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.txtUpdateCreator = new global::Gtk.Entry ();
		this.txtUpdateCreator.CanFocus = true;
		this.txtUpdateCreator.Name = "txtUpdateCreator";
		this.txtUpdateCreator.IsEditable = true;
		this.txtUpdateCreator.InvisibleChar = '●';
		this.hbox13.Add (this.txtUpdateCreator);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.txtUpdateCreator]));
		w62.Position = 1;
		this.vbox7.Add (this.hbox13);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox13]));
		w63.Position = 4;
		w63.Expand = false;
		w63.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label ();
		this.label17.WidthRequest = 100;
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Description:");
		this.hbox14.Add (this.label17);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label17]));
		w64.Position = 0;
		w64.Expand = false;
		w64.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.txtUpdateDescription = new global::Gtk.Entry ();
		this.txtUpdateDescription.CanFocus = true;
		this.txtUpdateDescription.Name = "txtUpdateDescription";
		this.txtUpdateDescription.IsEditable = true;
		this.txtUpdateDescription.InvisibleChar = '●';
		this.hbox14.Add (this.txtUpdateDescription);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.txtUpdateDescription]));
		w65.Position = 1;
		this.vbox7.Add (this.hbox14);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox14]));
		w66.Position = 5;
		w66.Expand = false;
		w66.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox ();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label ();
		this.label18.WidthRequest = 100;
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Category:");
		this.hbox15.Add (this.label18);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label18]));
		w67.Position = 0;
		w67.Expand = false;
		w67.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.txtUpdateCategory = new global::Gtk.Entry ();
		this.txtUpdateCategory.CanFocus = true;
		this.txtUpdateCategory.Name = "txtUpdateCategory";
		this.txtUpdateCategory.IsEditable = true;
		this.txtUpdateCategory.InvisibleChar = '●';
		this.hbox15.Add (this.txtUpdateCategory);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.txtUpdateCategory]));
		w68.Position = 1;
		this.vbox7.Add (this.hbox15);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox15]));
		w69.Position = 6;
		w69.Expand = false;
		w69.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.btnUpdate = new global::Gtk.Button ();
		this.btnUpdate.CanFocus = true;
		this.btnUpdate.Name = "btnUpdate";
		this.btnUpdate.UseUnderline = true;
		this.btnUpdate.Label = global::Mono.Unix.Catalog.GetString ("Update");
		this.vbox7.Add (this.btnUpdate);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.btnUpdate]));
		w70.Position = 7;
		w70.Expand = false;
		w70.Fill = false;
		this.nbTabs.Add (this.vbox7);
		global::Gtk.Notebook.NotebookChild w71 = ((global::Gtk.Notebook.NotebookChild)(this.nbTabs [this.vbox7]));
		w71.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Update");
		this.nbTabs.SetTabLabel (this.vbox7, this.label3);
		this.label3.ShowAll ();
		this.vpaned1.Add (this.nbTabs);
		global::Gtk.Paned.PanedChild w72 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.nbTabs]));
		w72.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frame2.BorderWidth = ((uint)(10));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		this.GtkAlignment1.RightPadding = ((uint)(12));
		this.GtkAlignment1.BottomPadding = ((uint)(6));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvLogging = new global::Gtk.TreeView ();
		this.tvLogging.CanFocus = true;
		this.tvLogging.Name = "tvLogging";
		this.GtkScrolledWindow.Add (this.tvLogging);
		this.GtkAlignment1.Add (this.GtkScrolledWindow);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel11 = new global::Gtk.Label ();
		this.GtkLabel11.Name = "GtkLabel11";
		this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Logging</b>");
		this.GtkLabel11.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel11;
		this.vpaned1.Add (this.frame2);
		this.vbox1.Add (this.vpaned1);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vpaned1]));
		w77.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 806;
		this.DefaultHeight = 664;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnSearch.Clicked += new global::System.EventHandler (this.OnBtnSearchClicked);
		this.btnEdit.Clicked += new global::System.EventHandler (this.OnBtnEditClicked);
		this.btnDelete.Clicked += new global::System.EventHandler (this.OnBtnDeleteClicked);
		this.btnInsert.Clicked += new global::System.EventHandler (this.OnBtnInsertClicked);
		this.btnUpdate.Clicked += new global::System.EventHandler (this.OnBtnUpdateClicked);
	}
}
